name: Semgrep Security Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and output SARIF
        run: semgrep --config=p/security-audit --config=p/secrets --config=p/ci --sarif --output=semgrep.sarif

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
