name: Semgrep

on:
  pull_request:
  push:
    branches: ["master", "main"]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      # ✅ Run Semgrep with community rulepacks
      - name: Run Semgrep Scan
        run: |
          semgrep scan \
            --config=p/security-audit \
            --config=p/secrets \
            --config=p/ci \
            --sarif --output=semgrep.sarif

      # ✅ Upload results to GitHub Code Scanning
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
