name: Semgrep Security Scan

on:
  pull_request:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Run diff-aware PR scan (requires SEMGREP_APP_TOKEN)
      - name: Run Semgrep CI
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # ✅ Upload SARIF to GitHub Code Scanning
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
