name: Semgrep Security Scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '20 17 * * *' # every day at 17:20 UTC

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4

      # ✅ PR: Diff-aware scan
      - name: Run Semgrep in CI mode (PR diff scan)
        if: github.event_name == 'pull_request'
        run: semgrep ci --sarif --output=semgrep.sarif --json --output=semgrep.json
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # ✅ Pushes / Cron: Full scan
      - name: Run full Semgrep scan (SARIF)
        if: github.event_name != 'pull_request'
        run: semgrep --config=p/security-audit --config=p/secrets --config=p/ci \
              --sarif --output=semgrep.sarif

      - name: Run full Semgrep scan (JSON)
        if: github.event_name != 'pull_request'
        run: semgrep --config=p/security-audit --config=p/secrets --config=p/ci \
              --json --output=semgrep.json

      # ✅ Upload SARIF to GitHub Code Scanning
      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      # ✅ Parse JSON & count findings
      - name: Count Semgrep findings
        id: counts
        run: |
          highs=$(jq '[.results[] | select(.extra.severity=="ERROR")] | length' semgrep.json)
          meds=$(jq '[.results[] | select(.extra.severity=="WARNING")] | length' semgrep.json)
          lows=$(jq '[.results[] | select(.extra.severity=="INFO")] | length' semgrep.json)
          echo "high=$highs" >> $GITHUB_OUTPUT
          echo "medium=$meds" >> $GITHUB_OUTPUT
          echo "low=$lows" >> $GITHUB_OUTPUT

      # ✅ Post PR Comment with summary
      - name: Add PR Comment with summary
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚡ **Semgrep Scan Results**
            - High severity: ${{ steps.counts.outputs.high }}
            - Medium severity: ${{ steps.counts.outputs.medium }}
            - Low severity: ${{ steps.counts.outputs.low }}
            
            📊 Full details:
            - Check the **Checks tab** for inline annotations
            - Or see **Security → Code scanning alerts**
