name: Semgrep

on:
  pull_request_target:
  push:
    branches: ["master", "main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      # ✅ Run Semgrep with community rulepacks (code + secrets + CI)
      - name: Run Semgrep Code Scan
        run: |
          semgrep scan \
            --config=p/security-audit \
            --config=p/secrets \
            --config=p/ci \
            --json --output=semgrep.json

      # ✅ Run Semgrep Supply Chain scan (dependencies)
      - name: Run Semgrep Supply Chain Scan
        run: |
          semgrep supply-chain \
            --json --output=semgrep-supply.json

      # ✅ Merge results (code + supply chain) into one JSON
      - name: Merge JSON results
        run: |
          jq -s '[.[0].results[], .[1].results[]] | {results: .}' semgrep.json semgrep-supply.json > semgrep-merged.json

      # ✅ Parse JSON results and count findings
      - name: Count Semgrep findings
        id: counts
        run: |
          criticals=$(jq '[.results[] | select(.extra.severity=="CRITICAL")] | length' semgrep-merged.json)
          highs=$(jq '[.results[] | select(.extra.severity=="ERROR" or .extra.severity=="HIGH")] | length' semgrep-merged.json)
          meds=$(jq '[.results[] | select(.extra.severity=="WARNING" or .extra.severity=="MEDIUM")] | length' semgrep-merged.json)
          lows=$(jq '[.results[] | select(.extra.severity=="INFO" or .extra.severity=="LOW")] | length' semgrep-merged.json)
          echo "critical=$criticals" >> $GITHUB_OUTPUT
          echo "high=$highs" >> $GITHUB_OUTPUT
          echo "medium=$meds" >> $GITHUB_OUTPUT
          echo "low=$lows" >> $GITHUB_OUTPUT

      # ✅ Comment summary directly on PR
      - name: Comment Semgrep results on PR
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚡ **Semgrep Security Scan**
            - 🟥 Critical severity: ${{ steps.counts.outputs.critical }}
            - 🔴 High severity: ${{ steps.counts.outputs.high }}
            - 🟠 Medium severity: ${{ steps.counts.outputs.medium }}
            - 🟢 Low severity: ${{ steps.counts.outputs.low }}

      
